### PR TITLE
Initial UI cleanup

### PR DESCRIPTION
**Pull request by tomhollander**
Replaced GridViews with ListViews - simpler multiselect experience
Updated login experience so you don't need to enter the tenant name before logging in

### CODE REVIEW

**Comment by tomhollander** [comment]
Also refactored the template generation out of the UI. Can do with more cleanup but it's a start :-)

**Comment by singhkays** [comment]
@PauloRamosGit Can you review?

**Comment by singhkays** [comment]
merging after OK from @PauloRamosGit

**Comment by singhkays** [comment]
@tomhollander Does this change the README and product pictures?

**Comment by tomhollander** [comment]
Yes, but Paulo's done it.

**Pull request merged**
